# Generated by Django 4.1.2 on 2022-10-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('Phone', models.IntegerField()),
                ('address', models.CharField(max_length=250)),
            ],
        ),
    ]
